  ('Euro Step', 'Skill-Tech', 'Finishing', 'Two-step lateral finish that evades primary shot blocker.', 4),
  ('Reverse Finish', 'Skill-Tech', 'Finishing', 'Use rim for protection: finish on far side of basket.', 3),
  ('Inside Hand Finish', 'Skill-Tech', 'Finishing', 'Finish with hand closest to rim for quick release.', 3),
  ('Float Finish', 'Skill-Tech', 'Finishing', 'Soft one‑hand push shot floated over rim protectors.', 3),
  ('Pro Hop', 'Skill-Tech', 'Finishing', 'Two‑foot lateral hop to split defenders before lift.', 4),
  ('Hop Gather', 'Skill-Tech', 'Footwork', 'Two‑foot hop to balance before shot or pass.', 2),
  ('Punch Pivot', 'Skill-Tech', 'Footwork', 'Aggressive pivot step to create space after catch.', 4),
  ('Snatch Back Dribble', 'Skill-Tech', 'Ball Handling', 'Hard pull‑back dribble to change direction & set up shot.', 4),
  ('Step‑Back 3', 'Skill-Tech', 'Shooting', 'Separation jump shot created off one‑step retreat.', 5),
  ('Escape Dribble', 'Skill-Tech', 'Ball Handling', 'Lateral dribble after pick‑up to open passing window.', 4),
  ('Jab Counter Shot', 'Skill-Tech', 'Shooting', 'Shot off a misleading jab step to freeze defender.', 4),
  ('Pace Change Dribble', 'Skill-Tech', 'Ball Handling', 'Deliberate slow‑fast rhythm to shift defender balance.', 2),
  ('Split‑Stance Landing', 'Skill-Tech', 'Footwork', 'Alternating‑foot landing to accelerate into next move.', 2),
  ('Hesi Pull‑Up', 'Skill-Tech', 'Shooting', 'Hesitation dribble into quick pull‑up jumper.', 3),
  ('Load Step Finish', 'Skill-Tech', 'Finishing', 'Transfer weight into strong plant before upward lift.', 3),
  ('Skip Read', 'Skill-Tact', 'Passing Decision', 'Cross‑court pass to opposite‑side advantage.', 4),
  ('Drift Corner Read', 'Skill-Tact', 'Relocation', 'Backpedal or slide to corner as driver penetrates.', 2),
  ('Shake Relocate', 'Skill-Tact', 'Relocation', 'Move along arc behind penetration to stay in vision.', 3),
  ('Cut & Replace', 'Skill-Tact', 'Off-Ball Movement', 'Occupy vacated space after teammate cuts.', 2),
  ('Scramble Kick', 'Skill-Tact', 'Advantage Play', 'Find open shooter when defense rotates late.', 4),
  ('Drive‑Kick‑Swing', 'Skill-Tact', 'Advantage Play', 'Extra pass after kick‑out to chase defensive close‑outs.', 3),
  ('Post Skip Read', 'Skill-Tact', 'Passing Decision', 'Strong‑side post to weak‑side skip for open 3.', 5),
  ('Paint Touch Decision', 'Skill-Tact', 'Penetration', 'Decision tree after ball enters paint area.', 3),
  ('Early Pitch Ahead', 'Skill-Tact', 'Transition', 'Advance pass to teammate beyond half‑court.', 2),
  ('Swing Re‑Screen', 'Skill-Tact', 'Secondary Action', 'Immediately flip screen angle after swing pass.', 5),
  ('Elastic Power', 'Physical', 'Power', 'Ability to store‑release force through tendons quickly.', 4),
  ('Deceleration Strength', 'Physical', 'Strength', 'Braking ability to stop on dime under control.', 3),
  ('Lateral Quickness', 'Physical', 'Agility', 'Explosive side‑to‑side movement capacity.', 2),
  ('Vertical Pop', 'Physical', 'Jump', 'Instant, repeatable vertical lift off one or two feet.', 3),
  ('Hip Mobility', 'Physical', 'Mobility', 'Range of motion allowing deep stance & rotation.', 1),
  ('Core Stability', 'Physical', 'Stability', 'Trunk control resisting unwanted motion.', 1),
  ('Anaerobic Capacity', 'Physical', 'Conditioning', 'High‑intensity work capacity 10–60 s bouts.', 4),
  ('Ankle Flexibility', 'Physical', 'Mobility', 'Dorsiflexion range critical for shin angle & balance.', 1),
  ('Confidence', 'Mental', 'Mindset', 'Belief in executing skill under pressure.', 1),
  ('Resilience', 'Mental', 'Mindset', 'Bounce back quickly after errors.', 2),
  ('Growth Mindset', 'Mental', 'Mindset', 'View mistakes as information for improvement.', 1),
  ('Competitive Toughness', 'Mental', 'Mindset', 'Maintain effort and focus in adverse situations.', 3),
  ('Focus Recovery', 'Mental', 'Cognitive', 'Speed at regaining attentional control after distraction.', 2),
  ('Calm Breathing', 'Mental', 'Regulation', 'Use breath to down‑regulate arousal in play.', 1),
  ('Weak‑Hand Only', 'Constraint', 'Ball Control', 'All dribbles & finishes must use non‑dominant hand.', 1),
  ('0.5 Second Decision', 'Constraint', 'Time', 'Ball must be shot, passed or driven within 0.5 s.', 4),
  ('One Touch Pass', 'Constraint', 'Passing', 'Immediate pass—no dribble or pivot allowed.', 3),
  ('No Help Defense', 'Constraint', 'Defense', 'Off‑ball defenders may not leave assignment.', 5),
  ('Two Pass Minimum', 'Constraint', 'Passing', 'Team must complete two passes before a shot.', 1),
  ('Lane Touch Before Shot', 'Constraint', 'Spacing', 'Ball must touch paint prior to any attempt.', 2),
  ('Corners Only', 'Constraint', 'Spacing', 'All three‑point attempts must come from corners.', 2),
  ('Crowd Noise Simulation', 'Environment', 'Stress', 'Audio overlay replicating hostile crowd.', 3),
  ('Uneven Floor Surface', 'Environment', 'Challenge', 'Add balance demand via rubber mats or turf patches.', 3),
  ('Fatigue Finisher', 'Environment', 'Load', 'High‑intensity drill at session end to test skill retention.', 4),
  ('Wet Ball Handling', 'Environment', 'Challenge', 'Use damp ball to amplify grip & control demands.', 2);
